/*
 * forwardservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package lazada_pkg

import "forwardservice_lib/configuration_pkg"

/*
 * Interface for the LAZADA_IMPL
 */
type LAZADA interface {
    MForwardServiceLazadaShopIdShopUrlHttpsWwwLazadaVnShopMoStore1601719537 (string) (error)
}

/*
 * Factory for the LAZADA interaface returning LAZADA_IMPL
 */
func NewLAZADA(config configuration_pkg.CONFIGURATION) *LAZADA_IMPL {
    client := new(LAZADA_IMPL)
    client.config = config
    return client
}