/*
 * forwardservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package ForwardServiceClient

import(
	"forwardservice_lib/configuration_pkg"
	"forwardservice_lib/shops_pkg"
	"forwardservice_lib/products_pkg"
	"forwardservice_lib/category_pkg"
	"forwardservice_lib/tiki_pkg"
	"forwardservice_lib/lazada_pkg"
)


/*
 * Interface for the FORWARDSERVICE_IMPL
 */
type FORWARDSERVICE interface {
    Shops()                 shops_pkg.SHOPS
    Products()              products_pkg.PRODUCTS
    Category()              category_pkg.CATEGORY
    Tiki()                  tiki_pkg.TIKI
    Lazada()                lazada_pkg.LAZADA
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the FORWARDSERVICE interface returning FORWARDSERVICE_IMPL
 */
func NewFORWARDSERVICE() FORWARDSERVICE {
    forwardServiceClient := new(FORWARDSERVICE_IMPL)
    forwardServiceClient.config = configuration_pkg.NewCONFIGURATION()

    return forwardServiceClient
}
