/*
 * forwardservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package shops_pkg

import "forwardservice_lib/configuration_pkg"

/*
 * Interface for the SHOPS_IMPL
 */
type SHOPS interface {
    ShopDetail (int64) (error)

    ShopCollections (int64, int64) (error)

    ShopProducts (int64, int64) (error)

    Malls () (error)
}

/*
 * Factory for the SHOPS interaface returning SHOPS_IMPL
 */
func NewSHOPS(config configuration_pkg.CONFIGURATION) *SHOPS_IMPL {
    client := new(SHOPS_IMPL)
    client.config = config
    return client
}