/*
 * forwardservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package products_pkg

import "forwardservice_lib/configuration_pkg"

/*
 * Interface for the PRODUCTS_IMPL
 */
type PRODUCTS interface {
    SearchProducts (string, int64, int64) (error)

    ProductDetail (int64, int64) (error)
}

/*
 * Factory for the PRODUCTS interaface returning PRODUCTS_IMPL
 */
func NewPRODUCTS(config configuration_pkg.CONFIGURATION) *PRODUCTS_IMPL {
    client := new(PRODUCTS_IMPL)
    client.config = config
    return client
}