/*
 * forwardservice_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package tiki_pkg

import "forwardservice_lib/configuration_pkg"

/*
 * Interface for the TIKI_IMPL
 */
type TIKI interface {
    GetShopProducts (string, int64) (error)
}

/*
 * Factory for the TIKI interaface returning TIKI_IMPL
 */
func NewTIKI(config configuration_pkg.CONFIGURATION) *TIKI_IMPL {
    client := new(TIKI_IMPL)
    client.config = config
    return client
}